### PR TITLE
Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @Suwayomi.

### CODE REVIEW

**Comment by Syer10** [comment]
Cant create a secret with the prefix GITHUB_, it seems its reserved

**Comment by vedantmgoyal2009** [comment]
You can keep it whatever you want and I'll update it in all PRs.

**Comment by Syer10** [comment]
I think keep GITHUB_TOKEN like it was since it doesnt need to be changed since its only releasing to the current repo, and name the secret WINGET_PUBLISH_KEY or something similar

**Comment by vedantmgoyal2009** [comment]
Releases have to be made using a PAT because of https://github.com/orgs/github-community/discussions/16244

**Comment by Syer10** [comment]
Huh, ok. Then just rename them WINGET_PUBLISH_PAT or something similar and I'll merge it 👍

**Comment by vedantmgoyal2009** [comment]
Done. Good to go 🚀 :)

**Pull request merged**
